### ISSUE TITLE
Select area does not work well with popover

### ISSUE THREAD

**Issue by mtuchi** [JSmith01/vue-selectable#11]
### Description
Am using this library to select a list of items and move them into a group, 
However when am using popover to select a destination group, the `cursor` can select items **beneath the popover** (On selection area) this makes it difficult to finish my feature as intended to do.

### Screenshot 
![kapture 2018-12-28 at 14 54 25](https://user-images.githubusercontent.com/6592749/50514665-c1980c80-0ab0-11e9-88a2-d3af7175012d.gif)

### Additional context
I have tried to increase the `z-index` of the popover, play around with `z-index` of `selecting-box` and `selection-area` as well with no lucky. 

Kindly assists on how i can block cursor from clicking the content beneath the popover.

**Comment by JSmith01** [comment]
Got it. Can you add [`stop` modifier](https://vuejs.org/v2/api/#v-on) (`event.stopPropagation()` call) for click handler? In `example4.html` I used this trick to enable "Google it" buttons.

**Comment by mtuchi** [comment]
@JSmith01 i have tried the stop modifier on my popover but still got nothing 
 ```
<el-menu @select="handleSelect">
  <el-menu-item
    v-for="(group, index) in getGroups"
    :key="index"
    :index="group.group"
    class="truncate"
    @mousedown.stop
  >
    <el-col :span="4">
      <img
        src="@/assets/icons/bag-delivery.svg"
        style="width: 60%; height: auto;"
      />
    </el-col>
    <span>{{ group.name }}</span>
  </el-menu-item>
</el-menu>

```

Am using [element-ui framework](http://element.eleme.io/#/)

**Comment by bborn** [comment]
Just FYI - I was able to solve a similar problem by stopping propagation on both the mousedown _and_ mouseup events.
