### ISSUE TITLE
Multiple use of selectbox

### ISSUE THREAD

**Issue by Sirpunpirate** [JSmith01/vue-selectable#13]
Hey Smith, is there a way to use the selectable more than once? I mean I want to select a group, then by pressing ctrl/cmd I want to select another group?

**Comment by JSmith01** [comment]
You can add additional logic on top of directive using `selectedSetter` (it can check on existing state). If you mean adding to selection, it supports this right out of the box.

**Comment by Sirpunpirate** [comment]
Nice, thanks man.
