### ISSUE TITLE
Shift-key selection support?

### ISSUE THREAD

**Issue by smellyshovel** [JSmith01/vue-selectable#14]
As can be seen from the examples, it's possible to select multiple items by holding the `ctrl` key. However I can't see if it's possible to do the same for batch-selection via holding the `shift` and clicking on start/end entries.

So is vue-selectable capable of doing this? Or, if not, can it be implemented?

**Comment by JSmith01** [comment]
Hello. Now it's not possible, however once it was planned feature. Unfortunately I cannot give you time estimate when this will be delivered.

**Comment by smellyshovel** [comment]
@JSmith01 Thank you for the response.
