### ISSUE TITLE
Poor interaction with elements that overlay selectable elements

### ISSUE THREAD

**Issue by spacewaffle** [JSmith01/vue-selectable#17]
When an element appears over a vue-selectable component, say a dropdown menu, modal, or popover, the vue-selectable component will hijack clicks from the overlay, preventing the user from interacting with the overlaid content. I believe this is because vue-selectable places event handers on the document object, then checks if the mouse is within the bounding box on mousedown, but not if the mousedown target is on the correct element. This method of checking for mousedown initial selection does not account for any kind of overlay, dom tree hierarchy, z-index, etc. The current workaround is to add @mousedown.stop and @mouseup.stop to the overlaid element. It would be better if we check if we've clicked on the right element on mousedown before starting a drag.

**Comment by JSmith01** [comment]
Thanks for commenting. I'll think if I can improve this.

**Comment by JSmith01** [comment]
The issue was fixed in the version 0.5, feel free to check the first example.

**Comment by spacewaffle** [comment]
Great, thank you for the fix!

**Comment by spacewaffle** [comment]
This isn't an issue, but a note for integrating 0.5.0. Thank you for that btw. When specifying the data constraint box, it's important to make it z-index -500 like in your example. This wasn't an issue for me previously until upgrading to 0.5.0. Otherwise you will be clicking the constraint box instead of the selection.

**Comment by JSmith01** [comment]
Ok, thanks for noting that.
