### ISSUE TITLE
cancel option like jqueryui?

### ISSUE THREAD

**Issue by mnooblet** [JSmith01/vue-selectable#5]
My selectable has input forms and other divs / buttons layered on top, atm it just swallows the mousedown event and selects the underlying item anyway, an option like cancel in jqueryui would come handy.

**Comment by JSmith01** [comment]
Please take a closer look to "[example4.html](https://github.com/JSmith01/vue-selectable/blob/master/examples2/example4.html)", it uses following construction to avoid this kind of problem:
`<button @click="googleIt(person)" @mousedown.stop>google it</button>`

So you have to add `@mousedown.stop` to every form element you have in selectable area. Please note if this helped.

**Comment by mnooblet** [comment]
that worked, thanks

**Comment by spacewaffle** [comment]
I have a lot of items that may potentially overlap with the selectable area. is there a way to avoid having to use @mousedown.stop and @mouseup.stop on every single item that could overlap?

**Comment by spacewaffle** [comment]
Nevermind, I solved the issue with data-constraint
