### ISSUE TITLE
setSelectableItems doesn't consider v-selectable position change 

### ISSUE THREAD

**Issue by mnooblet** [JSmith01/vue-selectable#6]
I've a selectable list below another list, if the above list changes and the v-selectable element changes position the selectbox is off.

this.$nextTick(() => selectable.setSelectableItems(this.$refs.vsel)) doesn't seem to fix it

**Comment by JSmith01** [comment]
Can you please provide full example for this scenario?

**Comment by mnooblet** [comment]
I added another wrapper and used the constraint option, now it works as intended.
